Added multi-layouts support

diff --git a/i3lock-fancy b/i3lock-fancy
--- a/i3lock-fancy
+++ b/i3lock-fancy
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # Author: Dolores Portalatin <hello@doloresportalatin.info>
-# Dependencies: imagemagick, i3lock-color-git, scrot, wmctrl (optional)
+# Dependencies: imagemagick, i3lock-color-git, scrot, wmctrl (optional), xkb-switch (optional)
 set -o errexit -o noclobber -o nounset
 
 hue=(-level "0%,100%,0.6")
@@ -12,6 +12,7 @@ shot=(import -window root)
 desktop=""
 i3lock_cmd=(i3lock -i "$image")
 shot_custom=false
+layout=""
 
 options="Options:
     -h, --help       This help menu.
@@ -30,6 +31,13 @@ options="Options:
                      Note: this option will not lock the screen, it displays
                      the list and exits immediately.
 
+    -L <layout>, --layout <layout>  Set layout before locking and restore last 
+    		     layout, if used -n/--nofork.
+
+    -a, --listlayouts Display a list of possible layouts for use with -L/--layout.
+                     Note: this option will not lock the screen, it displays
+                     the list and exits immediately.
+
     -n, --nofork     Do not fork i3lock after starting.
 
     --               Must be last option. Set command to use for taking a
@@ -40,7 +48,7 @@ options="Options:
 # move pipefail down as for some reason "convert -list font" returns 1
 set -o pipefail
 trap 'rm -f "$image"' EXIT
-temp="$(getopt -o :hdnpglt:f: -l desktop,help,listfonts,nofork,pixelate,greyscale,text:,font: --name "$0" -- "$@")"
+temp="$(getopt -o :hdnpglat:f:L: -l desktop,help,listfonts,nofork,pixelate,greyscale,listlayouts,text:,font:,layout: --name "$0" -- "$@")"
 eval set -- "$temp"
 
 # l10n support
@@ -81,6 +89,8 @@ while true ; do
         -l|--listfonts)
 	    convert -list font | awk -F: '/Font: / { print $2 }' | sort -du | command -- ${PAGER:-less}
 	    exit 0 ;;
+	-L|--layout) layout=$2 ; shift 2 ;;
+        -a|--listlayouts) echo -e "Possible layouts:\n$(xkb-switch -l)" ; exit 0 ;;
 	-n|--nofork) i3lock_cmd+=(--nofork) ; shift ;;
         --) shift; shot_custom=true; break ;;
         *) echo "error" ; exit 1 ;;
@@ -89,6 +99,14 @@ done
 
 if "$shot_custom" && [[ $# -gt 0 ]]; then
     shot=("$@");
+fi
+
+# check selected and save current layout
+if [[ $layout != "" ]]; then
+    if [[ $(xkb-switch -l) != *"$layout"* ]]; then
+        echo "Invalid layout. Please, check --layoutslist"; exit 1
+    fi
+    last_layout=$(xkb-switch)
 fi
 
 command -- "${shot[@]}" "$image"
@@ -125,10 +143,20 @@ convert "$image" "${hue[@]}" "${effect[@]}" -font "$font" -pointsize 26 -fill "$
 # the desktop) before locking.
 ${desktop} ${desktop:+-k on}
 
+# switch layout
+if [[ $layout != "" ]]; then
+    xkb-switch -s $layout
+fi
+
 # try to use i3lock with prepared parameters
 if ! "${i3lock_cmd[@]}" "${param[@]}" >/dev/null 2>&1; then
     # We have failed, lets get back to stock one
     "${i3lock_cmd[@]}"
+fi
+
+# restore layout after unlocking screen
+if [[ $layout != "" ]] && [[ ${i3lock_cmd[@]} == *"--nofork"* ]]; then
+    xkb-switch -s $last_layout 
 fi
 
 # As above, if we were passed -d/--desktop, we'll attempt to restore all windows
